import type { HomeAssistant } from "./types";

const STRINGS = {
  en: {
    weather_alerts: "Weather alerts",
    close: "Close",
    remove: "Remove",
    onset: "Onset",
    expires: "Expires",
    instructions: "Instructions",
    feels_like: "Feels like",
    humidity: "Humidity",
    wind_direction: "Wind direction",
    wind_direction_tip: "Wind direction {dir}",
    uv_index: "UV index",
    uv_cat_low: "Low",
    uv_cat_moderate: "Moderate",
    uv_cat_high: "High",
    uv_cat_very_high: "Very high",
    uv_cat_extreme: "Extreme",
    uv_cat_unknown: "Unknown",
    uv_advice_low: "No protection needed. You can safely stay outside.",
    uv_advice_moderate:
      "Protection required: seek shade during midday hours; wear a shirt, broad-spectrum sunscreen and a hat.",
    uv_advice_high:
      "Protection required: seek shade during midday hours; wear a shirt, broad-spectrum sunscreen and a hat.",
    uv_advice_very_high:
      "Extra protection required: avoid being outside during midday hours; shirt, broad-spectrum sunscreen and a hat are a must.",
    uv_advice_extreme:
      "Extra protection required: avoid being outside during midday hours; shirt, broad-spectrum sunscreen and a hat are a must.",
    uv_advice_unknown: "UV data unavailable.",
    pressure: "Pressure",
    cloud_coverage: "Cloud coverage",
    dew_point: "Dew point",
    visibility: "Visibility",
    precipitation: "Precipitation",
    precipitation_probability: "Precipitation probability",
    wind_gust: "Wind gust",
    wind_speed: "Wind speed",
    sunset: "Sunset",
    sunrise: "Sunrise",
    next_sun: "Next sunrise / sunset",
    sun_dawn: "Morning light",
    sun_dusk: "Evening light",
    sun_sunrise_today: "Sunrise today",
    sun_sunset_today: "Sunset today",
    sun_total_daylight: "Total daylight",
    current_conditions: "Current conditions",
    detail_no_chart: "No hourly forecast for this metric.",
    duration_hours_mins: "{hours} h {mins} min",
    duration_mins: "{mins} min",
    copy_current_unknown: "Current conditions unavailable.",
    copy_current_simple: "{condition} right now.",
    copy_current_range: "{condition}. High {high}{unit}, low {low}{unit} in the next 24 hours.",
    copy_humidity_dry: "Air feels dry.",
    copy_humidity_comfortable: "Comfortable humidity.",
    copy_humidity_humid: "Humidity is on the high side.",
    copy_humidity_muggy: "Air feels muggy.",
    copy_humidity_unknown: "Humidity data unavailable.",
    copy_wind_speed: "Beaufort {bft} from the {dir}.",
    copy_wind_gust: "Gusts up to Beaufort {bft}.",
    copy_wind_direction: "Wind from the {dir} at Beaufort {bft}.",
    copy_precip_next: "Precipitation expected around {time}.",
    copy_precip_none: "No significant precipitation in the hourly forecast.",
    copy_precip_prob_peak: "Peak chance {pct}% in the next 24 hours.",
    copy_precip_prob_low: "Low chance of precipitation ahead.",
    copy_cloud_clear: "Mostly clear skies.",
    copy_cloud_partly: "Partly cloudy.",
    copy_cloud_mostly: "Mostly cloudy.",
    copy_cloud_overcast: "Overcast.",
    copy_cloud_unknown: "Cloud cover data unavailable.",
    copy_uv_low: "Low UV — minimal protection needed.",
    copy_uv_moderate: "Moderate UV — use sunscreen if outside for a while.",
    copy_uv_high: "High UV — protection recommended.",
    copy_uv_very_high: "Very high UV — extra protection advised.",
    copy_uv_extreme: "Extreme UV — avoid midday sun if possible.",
    copy_uv_unknown: "UV data unavailable.",
    copy_pressure_low: "Pressure is relatively low.",
    copy_pressure_normal: "Pressure is in the normal range.",
    copy_pressure_high: "Pressure is relatively high.",
    copy_pressure_unknown: "Pressure data unavailable.",
    copy_visibility_fog: "Visibility is limited — fog or mist.",
    copy_visibility_haze: "Reduced visibility — haze possible.",
    copy_visibility_clear: "Good visibility.",
    copy_visibility_unknown: "Visibility data unavailable.",
    copy_sun_daylight: "{duration} of daylight remaining.",
    copy_sun_set_soon: "Sunset is approaching.",
    copy_sun_night: "Night — next sunrise shown above.",
    waiting: "Waiting for Home Assistant…",
    configure_entity: "Configure a weather entity for this card.",
    entity_not_found: "Entity not found",
    enable_section:
      "Enable a section in the card configuration to show weather content.",
    no_forecast: "No {mode} forecast data available on",
    forecast_failed: "Failed to load forecast",
    mode_daily: "daily",
    mode_hourly: "hourly",
    wind: "Wind",
    wind_tip: "Wind {speed} (Beaufort {bft})",
    beaufort: "Beaufort",
    active_warnings: "{count} active warnings",
    alerts_more: "+{count} more",
    alert_starts_in: "Starts in {duration}",
    alert_ends_in: "Ends in {duration}",
    alert_started_ago: "Started {duration} ago",
    alert_ended_ago: "Ended {duration} ago",
    chart_high: "High",
    chart_low: "Low",
    chart_temp: "Temp",
    chart_precip: "Precip",
    chart_precip_pct: "Precip %",
    legend_general: "General",
    legend_current: "Current weather",
    legend_daily: "Daily forecast",
    legend_hourly: "Hourly forecast",
    legend_alerts: "Weather alerts",
    legend_actions: "Actions",
    legend_sensors: "Optional sensors",
    weather_entity: "Weather entity",
    layout: "Layout",
    layout_default: "default",
    layout_compact: "compact",
    layout_minimal: "minimal",
    show_name: "Show name",
    name_placeholder: "Name (empty = entity label)",
    icon_style: "Icon style",
    animated_icons: "Animated icons",
    animated_background: "Animated background",
    show_current_weather: "Show current weather",
    current_detail_hint:
      "Detail chips only appear on the card when the weather entity or an override sensor provides a value. Availability varies by integration.",
    preset_available_details: "Available details",
    preset_all_details: "All details",
    preset_clear_all: "Clear all",
    footnote_missing_attrs:
      "* Not on this weather entity — add a sensor under Optional sensors below.",
    show_daily_forecast: "Show daily forecast",
    days: "Days",
    condition_icons: "Condition icons",
    show_hourly_forecast: "Show hourly forecast",
    hours: "Hours",
    prob_not_in_forecast: "probability not in forecast",
    prob_in_forecast: "probability in forecast",
    rainfall: "rainfall",
    probability: "probability",
    show_weather_alerts: "Show weather alerts",
    alerts_choose_hint:
      "Choose where alerts come from. Recommended: CAP Alerts (one device for your region). Europe alternative: a MeteoAlarm binary sensor.",
    alert_source: "Alert source",
    cap_alerts_device: "CAP Alerts device",
    alert_entities: "Alert entities",
    cap_device_hint:
      "Pick any entity on your CAP Alerts device. The card uses that device and includes all active alerts on it — not just the one entity you pick.",
    cap_device_auto: "One CAP Alerts device was found.",
    alert_entities_hint:
      "Select one or more MeteoAlarm or CAP Alerts entities. All active warnings from every entity are merged on the card.",
    add_another_entity: "Add another entity",
    actions_default_hint:
      "Tap opens the current-conditions detail sheet when not set. Use tap_action: more-info to restore Home Assistant’s entity dialog.",
    action_reset_default: "Reset to default",
    tap_action: "Tap action",
    hold_action: "Hold action",
    double_tap_action: "Double tap action",
    sensors_override_hint:
      "Override values from the weather entity with dedicated sensors. Condition override is useful for testing backgrounds.",
    condition: "Condition",
    temperature: "Temperature",
    wind_bearing: "Wind bearing",
    sun: "Sun",
    phase_new: "New",
    phase_update: "Update",
    phase_cancel: "Cancel",
    phase_expired: "Expired",
  },
  is: {
    weather_alerts: "Veðurviðvaranir",
    close: "Loka",
    remove: "Fjarlægja",
    onset: "Byrjun",
    expires: "Rennur út",
    instructions: "Leiðbeiningar",
    feels_like: "Skynjanlegt",
    humidity: "Raki",
    wind_direction: "Vindstefna",
    wind_direction_tip: "Vindstefna {dir}",
    uv_index: "UV vísitala",
    uv_cat_low: "Lágt",
    uv_cat_moderate: "Miðlungs",
    uv_cat_high: "Hátt",
    uv_cat_very_high: "Mjög hátt",
    uv_cat_extreme: "Öfgafullt",
    uv_cat_unknown: "Óþekkt",
    uv_advice_low: "Engin vernd þörf. Þú getur verið úti á öruggan hátt.",
    uv_advice_moderate:
      "Vernd krafist: leitaðu í skugga á miðjum degi; notaðu skyrtu, breiðvirka sólarvörn og hatt.",
    uv_advice_high:
      "Vernd krafist: leitaðu í skugga á miðjum degi; notaðu skyrtu, breiðvirka sólarvörn og hatt.",
    uv_advice_very_high:
      "Aukin vernd krafist: forðastu að vera úti á miðjum degi; skyrta, breiðvirk sólarvörn og hattur eru nauðsynleg.",
    uv_advice_extreme:
      "Aukin vernd krafist: forðastu að vera úti á miðjum degi; skyrta, breiðvirk sólarvörn og hattur eru nauðsynleg.",
    uv_advice_unknown: "UV gögn ekki tiltæk.",
    pressure: "Loftþyngd",
    cloud_coverage: "Skýjahula",
    dew_point: "Daggpunktur",
    visibility: "Skyggni",
    precipitation: "Úrkoma",
    precipitation_probability: "Líkur á úrkomu",
    wind_gust: "Vindhviður",
    wind_speed: "Vindhraði",
    sunset: "Sólsetur",
    sunrise: "Sólarupprás",
    next_sun: "Næsta sólarupprás / sólsetur",
    sun_dawn: "Morgunljós",
    sun_dusk: "Náttljós",
    sun_sunrise_today: "Sólarupprás í dag",
    sun_sunset_today: "Sólsetur í dag",
    sun_total_daylight: "Heildar dagsbirta",
    current_conditions: "Núverandi ástand",
    detail_no_chart: "Engin klukkustundarspá fyrir þetta gildi.",
    duration_hours_mins: "{hours} klst {mins} mín",
    duration_mins: "{mins} mín",
    copy_current_unknown: "Núverandi ástand ekki tiltækt.",
    copy_current_simple: "{condition} núna.",
    copy_current_range: "{condition}. Hátt {high}{unit}, lágt {low}{unit} næstu 24 klst.",
    copy_humidity_dry: "Þurrt loft.",
    copy_humidity_comfortable: "Þægilegur raki.",
    copy_humidity_humid: "Mikill raki.",
    copy_humidity_muggy: "Þungbært loft.",
    copy_humidity_unknown: "Rakagögn ekki tiltæk.",
    copy_wind_speed: "Beaufort {bft} af {dir}.",
    copy_wind_gust: "Hviður allt að Beaufort {bft}.",
    copy_wind_direction: "Vindur af {dir} við Beaufort {bft}.",
    copy_precip_next: "Úrkoma vænt um {time}.",
    copy_precip_none: "Engin veruleg úrkoma í klukkustundarspá.",
    copy_precip_prob_peak: "Hámarkslíkur {pct}% næstu 24 klst.",
    copy_precip_prob_low: "Lítil líkur á úrkomu framundan.",
    copy_cloud_clear: "Mostly heiðskírt.",
    copy_cloud_partly: "Skýjað að hluta.",
    copy_cloud_mostly: "Mostly skýjað.",
    copy_cloud_overcast: "Alskýjað.",
    copy_cloud_unknown: "Skýjahula ekki tiltæk.",
    copy_uv_low: "Lítil UV — lítill varnir þarf.",
    copy_uv_moderate: "Miðlungs UV — sólarvörn ef lengi úti.",
    copy_uv_high: "Há UV — varnir mælt með.",
    copy_uv_very_high: "Mjög há UV — auknar varnir.",
    copy_uv_extreme: "Öfgafull UV — forðast hádegi ef hægt.",
    copy_uv_unknown: "UV gögn ekki tiltæk.",
    copy_pressure_low: "Lítil loftþyngd.",
    copy_pressure_normal: "Loftþyngd í eðlilegu horfi.",
    copy_pressure_high: "Há loftþyngd.",
    copy_pressure_unknown: "Loftþyngd ekki tiltæk.",
    copy_visibility_fog: "Takmarkað skyggni — þoka.",
    copy_visibility_haze: "Minnkað skyggni.",
    copy_visibility_clear: "Gott skyggni.",
    copy_visibility_unknown: "Skyggni ekki tiltæk.",
    copy_sun_daylight: "{duration} dagsbirtu eftir.",
    copy_sun_set_soon: "Sólsetur nálgast.",
    copy_sun_night: "Nótt — næsta sólarupprás hér fyrir ofan.",
    waiting: "Bíð eftir Home Assistant…",
    configure_entity: "Stilltu veður einingu fyrir þetta spjald.",
    entity_not_found: "Eining fannst ekki",
    enable_section:
      "Virkjaðu hluta í stillingum spjaldsins til að sýna veður.",
    no_forecast: "Engin {mode} spá tiltæk á",
    forecast_failed: "Mistókst að hlaða spá",
    mode_daily: "dagleg",
    mode_hourly: "klukkustundar",
    wind: "Vindur",
    wind_tip: "Vindur {speed} (Beaufort {bft})",
    beaufort: "Beaufort",
    active_warnings: "{count} virkar viðvaranir",
    alerts_more: "+{count} til viðbótar",
    alert_starts_in: "Hefst eftir {duration}",
    alert_ends_in: "Lýkur eftir {duration}",
    alert_started_ago: "Hófst fyrir {duration} síðan",
    alert_ended_ago: "Lauk fyrir {duration} síðan",
    chart_high: "Hátt",
    chart_low: "Lágt",
    chart_temp: "Hitastig",
    chart_precip: "Úrkoma",
    chart_precip_pct: "Úrkoma %",
    legend_general: "Almennt",
    legend_current: "Núverandi veður",
    legend_daily: "Dagleg spá",
    legend_hourly: "Klukkustundarspá",
    legend_alerts: "Veðurviðvaranir",
    legend_actions: "Aðgerðir",
    legend_sensors: "Valfrjálsar skynjarar",
    weather_entity: "Veður eining",
    layout: "Útlit",
    layout_default: "sjálfgefið",
    layout_compact: "þjappað",
    layout_minimal: "lágmark",
    show_name: "Sýna nafn",
    name_placeholder: "Nafn (autt = heiti einingar)",
    icon_style: "Táknstíll",
    animated_icons: "Hreyfð tákn",
    animated_background: "Hreyfður bakgrunnur",
    show_current_weather: "Sýna núverandi veður",
    current_detail_hint:
      "Smáatriðakubbar birtast aðeins þegar veðureining eða skynjarar hafa gildi.",
    preset_available_details: "Tiltækar upplýsingar",
    preset_all_details: "Allar upplýsingar",
    preset_clear_all: "Hreinsa allt",
    footnote_missing_attrs:
      "* Ekki á þessari veðureiningu — bættu við skynjara hér fyrir neðan.",
    show_daily_forecast: "Sýna daglega spá",
    days: "Dagar",
    condition_icons: "Veðurtákn",
    show_hourly_forecast: "Sýna klukkustundarspá",
    hours: "Klukkustundir",
    prob_not_in_forecast: "líkur ekki í spá",
    prob_in_forecast: "líkur í spá",
    rainfall: "úrkoma",
    probability: "líkur",
    show_weather_alerts: "Sýna veðurviðvaranir",
    alerts_choose_hint:
      "Veldu uppruna viðvarana. Mælt með CAP Alerts. Evrópuvalkostur: MeteoAlarm skynjar.",
    alert_source: "Uppruni viðvarana",
    cap_alerts_device: "CAP Alerts tæki",
    alert_entities: "Viðvaranaeiningar",
    cap_device_hint:
      "Veldu einingu á CAP Alerts tækinu þínu. Spjaldið notar allar virkar viðvaranir á tækinu.",
    cap_device_auto: "Eitt CAP Alerts tæki fannst.",
    alert_entities_hint:
      "Veldu eina eða fleiri MeteoAlarm eða CAP einingar. Allar virkar viðvaranir sameinast.",
    add_another_entity: "Bæta við einingu",
    actions_default_hint:
      "Smella opnar nánari upplýsingar um núverandi veður. Notaðu tap_action: more-info til að opna HA einingaglugga.",
    action_reset_default: "Endurstilla sjálfgefið",
    tap_action: "Smella",
    hold_action: "Halda inni",
    double_tap_action: "Tvísmella",
    sensors_override_hint:
      "Skipta um gildi með sérstökum skynjurum. Veðurástand er gagnlegt til prófs.",
    condition: "Ástand",
    temperature: "Hitastig",
    wind_bearing: "Vindstefna (gráður)",
    sun: "Sól",
    phase_new: "Nýtt",
    phase_update: "Uppfærsla",
    phase_cancel: "Aflýst",
    phase_expired: "Útrunnið",
  },
  nl: {
    weather_alerts: "Weerswaarschuwingen",
    close: "Sluiten",
    remove: "Verwijderen",
    onset: "Begin",
    expires: "Verloopt",
    instructions: "Instructies",
    feels_like: "Gevoelstemperatuur",
    humidity: "Vochtigheid",
    wind_direction: "Windrichting",
    wind_direction_tip: "Windrichting {dir}",
    uv_index: "UV-index",
    uv_cat_low: "Laag",
    uv_cat_moderate: "Matig",
    uv_cat_high: "Hoog",
    uv_cat_very_high: "Zeer hoog",
    uv_cat_extreme: "Extreem",
    uv_cat_unknown: "Onbekend",
    uv_advice_low:
      "Geen bescherming nodig. Je kunt veilig buiten zijn.",
    uv_advice_moderate:
      "Bescherming vereist: zoek schaduw tijdens de middaguren; draag een shirt, breedspectrum-zonnebrandcrème en een hoed.",
    uv_advice_high:
      "Bescherming vereist: zoek schaduw tijdens de middaguren; draag een shirt, breedspectrum-zonnebrandcrème en een hoed.",
    uv_advice_very_high:
      "Extra bescherming vereist: vermijd buiten zijn tijdens de middaguren; shirt, breedspectrum-zonnebrandcrème en hoed zijn een must.",
    uv_advice_extreme:
      "Extra bescherming vereist: vermijd buiten zijn tijdens de middaguren; shirt, breedspectrum-zonnebrandcrème en hoed zijn een must.",
    uv_advice_unknown: "UV-gegevens niet beschikbaar.",
    pressure: "Luchtdruk",
    cloud_coverage: "Bewolking",
    dew_point: "Dauwpunt",
    visibility: "Zicht",
    precipitation: "Neerslag",
    precipitation_probability: "Neerslagkans",
    wind_gust: "Windstoot",
    wind_speed: "Windsnelheid",
    sunset: "Zonsondergang",
    sunrise: "Zonsopgang",
    next_sun: "Volgende zonsopgang / zonsondergang",
    sun_dawn: "Ochtendlicht",
    sun_dusk: "Avondlicht",
    sun_sunrise_today: "Zonsopgang vandaag",
    sun_sunset_today: "Zonsondergang vandaag",
    sun_total_daylight: "Totaal daglicht",
    current_conditions: "Huidige omstandigheden",
    detail_no_chart: "Geen uurlijkse prognose voor deze waarde.",
    duration_hours_mins: "{hours} u {mins} min",
    duration_mins: "{mins} min",
    copy_current_unknown: "Huidige omstandigheden niet beschikbaar.",
    copy_current_simple: "{condition} op dit moment.",
    copy_current_range: "{condition}. Max {high}{unit}, min {low}{unit} komende 24 uur.",
    copy_humidity_dry: "Droge lucht.",
    copy_humidity_comfortable: "Comfortabele luchtvochtigheid.",
    copy_humidity_humid: "Hoge luchtvochtigheid.",
    copy_humidity_muggy: "Benauwde lucht.",
    copy_humidity_unknown: "Vochtigheidsgegevens niet beschikbaar.",
    copy_wind_speed: "Beaufort {bft} uit {dir}.",
    copy_wind_gust: "Windstoten tot Beaufort {bft}.",
    copy_wind_direction: "Wind uit {dir} op Beaufort {bft}.",
    copy_precip_next: "Neerslag verwacht rond {time}.",
    copy_precip_none: "Geen noemenswaardige neerslag in de uurprognose.",
    copy_precip_prob_peak: "Piek kans {pct}% komende 24 uur.",
    copy_precip_prob_low: "Kleine kans op neerslag.",
    copy_cloud_clear: "Overwegend helder.",
    copy_cloud_partly: "Gedeeltelijk bewolkt.",
    copy_cloud_mostly: "Overwegend bewolkt.",
    copy_cloud_overcast: "Betrokken.",
    copy_cloud_unknown: "Bewolking niet beschikbaar.",
    copy_uv_low: "Lage UV — weinig bescherming nodig.",
    copy_uv_moderate: "Matige UV — zonnebrand bij lang buiten zijn.",
    copy_uv_high: "Hoge UV — bescherming aanbevolen.",
    copy_uv_very_high: "Zeer hoge UV — extra bescherming.",
    copy_uv_extreme: "Extreme UV — vermijd middagzon indien mogelijk.",
    copy_uv_unknown: "UV-gegevens niet beschikbaar.",
    copy_pressure_low: "Relatief lage luchtdruk.",
    copy_pressure_normal: "Luchtdruk in normaal bereik.",
    copy_pressure_high: "Relatief hoge luchtdruk.",
    copy_pressure_unknown: "Luchtdruk niet beschikbaar.",
    copy_visibility_fog: "Beperkt zicht — mist.",
    copy_visibility_haze: "Verminderd zicht — nevel mogelijk.",
    copy_visibility_clear: "Goed zicht.",
    copy_visibility_unknown: "Zicht niet beschikbaar.",
    copy_sun_daylight: "Nog {duration} daglicht.",
    copy_sun_set_soon: "Zonsondergang nadert.",
    copy_sun_night: "Nacht — volgende zonsopgang hierboven.",
    waiting: "Wachten op Home Assistant…",
    configure_entity: "Configureer een weerentiteit voor deze kaart.",
    entity_not_found: "Entiteit niet gevonden",
    enable_section:
      "Schakel een sectie in via de kaartconfiguratie om weer te tonen.",
    no_forecast: "Geen {mode} prognose beschikbaar op",
    forecast_failed: "Prognose laden mislukt",
    mode_daily: "dagelijkse",
    mode_hourly: "uurlijkse",
    wind: "Wind",
    wind_tip: "Wind {speed} (Beaufort {bft})",
    beaufort: "Beaufort",
    active_warnings: "{count} actieve waarschuwingen",
    alerts_more: "+{count} meer",
    alert_starts_in: "Begint over {duration}",
    alert_ends_in: "Eindigt over {duration}",
    alert_started_ago: "Begonnen {duration} geleden",
    alert_ended_ago: "Geëindigd {duration} geleden",
    chart_high: "Max",
    chart_low: "Min",
    chart_temp: "Temp",
    chart_precip: "Neerslag",
    chart_precip_pct: "Neerslag %",
    legend_general: "Algemeen",
    legend_current: "Huidig weer",
    legend_daily: "Dagelijkse prognose",
    legend_hourly: "Uurlijkse prognose",
    legend_alerts: "Weerswaarschuwingen",
    legend_actions: "Acties",
    legend_sensors: "Optionele sensoren",
    weather_entity: "Weerentiteit",
    layout: "Layout",
    layout_default: "standaard",
    layout_compact: "compact",
    layout_minimal: "minimaal",
    show_name: "Naam tonen",
    name_placeholder: "Naam (leeg = entiteitslabel)",
    icon_style: "Pictogramstijl",
    animated_icons: "Geanimeerde pictogrammen",
    animated_background: "Geanimeerde achtergrond",
    show_current_weather: "Huidig weer tonen",
    current_detail_hint:
      "Detailchips verschijnen alleen wanneer de weerentiteit of een sensor een waarde heeft.",
    preset_available_details: "Beschikbare details",
    preset_all_details: "Alle details",
    preset_clear_all: "Alles wissen",
    footnote_missing_attrs:
      "* Niet op deze weerentiteit — voeg een sensor toe onder Optionele sensoren.",
    show_daily_forecast: "Dagelijkse prognose tonen",
    days: "Dagen",
    condition_icons: "Weerpictogrammen",
    show_hourly_forecast: "Uurlijkse prognose tonen",
    hours: "Uren",
    prob_not_in_forecast: "kans niet in prognose",
    prob_in_forecast: "kans in prognose",
    rainfall: "neerslag",
    probability: "kans",
    show_weather_alerts: "Weerswaarschuwingen tonen",
    alerts_choose_hint:
      "Kies de bron. Aanbevolen: CAP Alerts. Europees alternatief: MeteoAlarm sensor.",
    alert_source: "Waarschuwingsbron",
    cap_alerts_device: "CAP Alerts-apparaat",
    alert_entities: "Waarschuwingsentiteiten",
    cap_device_hint:
      "Kies een entiteit op je CAP Alerts-apparaat. De kaart gebruikt alle actieve waarschuwingen op dat apparaat.",
    cap_device_auto: "Eén CAP Alerts-apparaat gevonden.",
    alert_entities_hint:
      "Selecteer een of meer MeteoAlarm- of CAP-entiteiten. Alle actieve waarschuwingen worden samengevoegd.",
    add_another_entity: "Nog een entiteit toevoegen",
    actions_default_hint:
      "Tikken opent het detailvenster voor huidig weer. Gebruik tap_action: more-info voor het HA-entiteitsvenster.",
    action_reset_default: "Standaard herstellen",
    tap_action: "Tikactie",
    hold_action: "Ingedrukt houden",
    double_tap_action: "Dubbeltikactie",
    sensors_override_hint:
      "Overschrijf waarden met aparte sensoren. Conditie-override is handig om achtergronden te testen.",
    condition: "Conditie",
    temperature: "Temperatuur",
    wind_bearing: "Windrichting (graden)",
    sun: "Zon",
    phase_new: "Nieuw",
    phase_update: "Update",
    phase_cancel: "Geannuleerd",
    phase_expired: "Verlopen",
  },
} as const;

export type LocalizeKey = keyof typeof STRINGS.en;

function localeBase(language?: string): keyof typeof STRINGS {
  if (!language) return "en";
  const base = language.split("-")[0]?.toLowerCase();
  if (base === "is" || base === "nl") return base;
  return "en";
}

export function resolveLanguage(hass?: HomeAssistant): string | undefined {
  if (!hass) return undefined;
  return (
    hass.locale?.language ?? hass.language ?? hass.config.language ?? undefined
  );
}

export function localize(
  key: LocalizeKey,
  language?: string,
  vars?: Record<string, string>,
): string {
  const lang = localeBase(language);
  let text: string = STRINGS[lang][key] ?? STRINGS.en[key];
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replaceAll(`{${k}}`, v);
    }
  }
  return text;
}

/** Localized layout option label. */
export function layoutLabel(
  layout: string,
  language?: string,
): string {
  const key = `layout_${layout}` as LocalizeKey;
  if (key in STRINGS.en) {
    return localize(key, language);
  }
  return layout;
}
