import type { HomeAssistant } from "./types";

const STRINGS = {
  en: {
    weather_alerts: "Weather alerts",
    close: "Close",
    remove: "Remove",
    onset: "Onset",
    expires: "Expires",
    instructions: "Instructions",
    feels_like: "Feels like",
    humidity: "Humidity",
    wind_direction: "Wind direction",
    wind_direction_tip: "Wind direction {dir}",
    uv_index: "UV index",
    pressure: "Pressure",
    cloud_coverage: "Cloud coverage",
    dew_point: "Dew point",
    visibility: "Visibility",
    precipitation: "Precipitation",
    precipitation_probability: "Precipitation probability",
    wind_gust: "Wind gust",
    wind_speed: "Wind speed",
    sunset: "Sunset",
    sunrise: "Sunrise",
    next_sun: "Next sunrise / sunset",
    waiting: "Waiting for Home Assistant…",
    configure_entity: "Configure a weather entity for this card.",
    entity_not_found: "Entity not found",
    enable_section:
      "Enable a section in the card configuration to show weather content.",
    no_forecast: "No {mode} forecast data available on",
    forecast_failed: "Failed to load forecast",
    mode_daily: "daily",
    mode_hourly: "hourly",
    wind: "Wind",
    wind_tip: "Wind {speed} (Beaufort {bft})",
    beaufort: "Beaufort",
    active_warnings: "{count} active warnings",
    alert_starts_in: "Starts in {duration}",
    alert_ends_in: "Ends in {duration}",
    alert_started_ago: "Started {duration} ago",
    alert_ended_ago: "Ended {duration} ago",
    chart_high: "High",
    chart_low: "Low",
    chart_temp: "Temp",
    chart_precip: "Precip",
    chart_precip_pct: "Precip %",
    legend_general: "General",
    legend_current: "Current weather",
    legend_daily: "Daily forecast",
    legend_hourly: "Hourly forecast",
    legend_alerts: "Weather alerts",
    legend_actions: "Actions",
    legend_sensors: "Optional sensors",
    weather_entity: "Weather entity",
    layout: "Layout",
    layout_default: "default",
    layout_compact: "compact",
    layout_minimal: "minimal",
    show_name: "Show name",
    name_placeholder: "Name (empty = entity label)",
    icon_style: "Icon style",
    animated_icons: "Animated icons",
    animated_background: "Animated background",
    show_current_weather: "Show current weather",
    current_detail_hint:
      "Detail chips only appear on the card when the weather entity or an override sensor provides a value. Availability varies by integration.",
    preset_available_details: "Available details",
    preset_all_details: "All details",
    preset_clear_all: "Clear all",
    footnote_missing_attrs:
      "* Not on this weather entity — add a sensor under Optional sensors below.",
    show_daily_forecast: "Show daily forecast",
    days: "Days",
    condition_icons: "Condition icons",
    show_hourly_forecast: "Show hourly forecast",
    hours: "Hours",
    prob_not_in_forecast: "probability not in forecast",
    prob_in_forecast: "probability in forecast",
    rainfall: "rainfall",
    probability: "probability",
    show_weather_alerts: "Show weather alerts",
    alerts_choose_hint:
      "Choose where alerts come from. Recommended: CAP Alerts (one device for your region). Europe alternative: a MeteoAlarm binary sensor.",
    alert_source: "Alert source",
    cap_alerts_device: "CAP Alerts device",
    alert_entities: "Alert entities",
    cap_device_hint:
      "Pick any entity on your CAP Alerts device. The card uses that device and includes all active alerts on it — not just the one entity you pick.",
    cap_device_auto: "One CAP Alerts device was found.",
    alert_entities_hint:
      "Select one or more MeteoAlarm or CAP Alerts entities. All active warnings from every entity are merged on the card.",
    add_another_entity: "Add another entity",
    actions_default_hint:
      "Tap defaults to more-info on the weather entity when not set.",
    tap_action: "Tap action",
    hold_action: "Hold action",
    double_tap_action: "Double tap action",
    sensors_override_hint:
      "Override values from the weather entity with dedicated sensors. Condition override is useful for testing backgrounds.",
    condition: "Condition",
    temperature: "Temperature",
    wind_bearing: "Wind bearing",
    sun: "Sun",
    phase_new: "New",
    phase_update: "Update",
    phase_cancel: "Cancel",
    phase_expired: "Expired",
  },
  is: {
    weather_alerts: "Veðurviðvaranir",
    close: "Loka",
    remove: "Fjarlægja",
    onset: "Byrjun",
    expires: "Rennur út",
    instructions: "Leiðbeiningar",
    feels_like: "Skynjanlegt",
    humidity: "Raki",
    wind_direction: "Vindstefna",
    wind_direction_tip: "Vindstefna {dir}",
    uv_index: "UV vísitala",
    pressure: "Loftþyngd",
    cloud_coverage: "Skýjahula",
    dew_point: "Daggpunktur",
    visibility: "Skyggni",
    precipitation: "Úrkoma",
    precipitation_probability: "Líkur á úrkomu",
    wind_gust: "Vindhviður",
    wind_speed: "Vindhraði",
    sunset: "Sólsetur",
    sunrise: "Sólarupprás",
    next_sun: "Næsta sólarupprás / sólsetur",
    waiting: "Bíð eftir Home Assistant…",
    configure_entity: "Stilltu veður einingu fyrir þetta spjald.",
    entity_not_found: "Eining fannst ekki",
    enable_section:
      "Virkjaðu hluta í stillingum spjaldsins til að sýna veður.",
    no_forecast: "Engin {mode} spá tiltæk á",
    forecast_failed: "Mistókst að hlaða spá",
    mode_daily: "dagleg",
    mode_hourly: "klukkustundar",
    wind: "Vindur",
    wind_tip: "Vindur {speed} (Beaufort {bft})",
    beaufort: "Beaufort",
    active_warnings: "{count} virkar viðvaranir",
    alert_starts_in: "Hefst eftir {duration}",
    alert_ends_in: "Lýkur eftir {duration}",
    alert_started_ago: "Hófst fyrir {duration} síðan",
    alert_ended_ago: "Lauk fyrir {duration} síðan",
    chart_high: "Hátt",
    chart_low: "Lágt",
    chart_temp: "Hitastig",
    chart_precip: "Úrkoma",
    chart_precip_pct: "Úrkoma %",
    legend_general: "Almennt",
    legend_current: "Núverandi veður",
    legend_daily: "Dagleg spá",
    legend_hourly: "Klukkustundarspá",
    legend_alerts: "Veðurviðvaranir",
    legend_actions: "Aðgerðir",
    legend_sensors: "Valfrjálsar skynjarar",
    weather_entity: "Veður eining",
    layout: "Útlit",
    layout_default: "sjálfgefið",
    layout_compact: "þjappað",
    layout_minimal: "lágmark",
    show_name: "Sýna nafn",
    name_placeholder: "Nafn (autt = heiti einingar)",
    icon_style: "Táknstíll",
    animated_icons: "Hreyfð tákn",
    animated_background: "Hreyfður bakgrunnur",
    show_current_weather: "Sýna núverandi veður",
    current_detail_hint:
      "Smáatriðakubbar birtast aðeins þegar veðureining eða skynjarar hafa gildi.",
    preset_available_details: "Tiltækar upplýsingar",
    preset_all_details: "Allar upplýsingar",
    preset_clear_all: "Hreinsa allt",
    footnote_missing_attrs:
      "* Ekki á þessari veðureiningu — bættu við skynjara hér fyrir neðan.",
    show_daily_forecast: "Sýna daglega spá",
    days: "Dagar",
    condition_icons: "Veðurtákn",
    show_hourly_forecast: "Sýna klukkustundarspá",
    hours: "Klukkustundir",
    prob_not_in_forecast: "líkur ekki í spá",
    prob_in_forecast: "líkur í spá",
    rainfall: "úrkoma",
    probability: "líkur",
    show_weather_alerts: "Sýna veðurviðvaranir",
    alerts_choose_hint:
      "Veldu uppruna viðvarana. Mælt með CAP Alerts. Evrópuvalkostur: MeteoAlarm skynjar.",
    alert_source: "Uppruni viðvarana",
    cap_alerts_device: "CAP Alerts tæki",
    alert_entities: "Viðvaranaeiningar",
    cap_device_hint:
      "Veldu einingu á CAP Alerts tækinu þínu. Spjaldið notar allar virkar viðvaranir á tækinu.",
    cap_device_auto: "Eitt CAP Alerts tæki fannst.",
    alert_entities_hint:
      "Veldu eina eða fleiri MeteoAlarm eða CAP einingar. Allar virkar viðvaranir sameinast.",
    add_another_entity: "Bæta við einingu",
    actions_default_hint:
      "Smella opnar sjálfgefið nánari upplýsingar um veðureininguna.",
    tap_action: "Smella",
    hold_action: "Halda inni",
    double_tap_action: "Tvísmella",
    sensors_override_hint:
      "Skipta um gildi með sérstökum skynjurum. Veðurástand er gagnlegt til prófs.",
    condition: "Ástand",
    temperature: "Hitastig",
    wind_bearing: "Vindstefna (gráður)",
    sun: "Sól",
    phase_new: "Nýtt",
    phase_update: "Uppfærsla",
    phase_cancel: "Aflýst",
    phase_expired: "Útrunnið",
  },
  nl: {
    weather_alerts: "Weerswaarschuwingen",
    close: "Sluiten",
    remove: "Verwijderen",
    onset: "Begin",
    expires: "Verloopt",
    instructions: "Instructies",
    feels_like: "Gevoelstemperatuur",
    humidity: "Vochtigheid",
    wind_direction: "Windrichting",
    wind_direction_tip: "Windrichting {dir}",
    uv_index: "UV-index",
    pressure: "Luchtdruk",
    cloud_coverage: "Bewolking",
    dew_point: "Dauwpunt",
    visibility: "Zicht",
    precipitation: "Neerslag",
    precipitation_probability: "Neerslagkans",
    wind_gust: "Windstoot",
    wind_speed: "Windsnelheid",
    sunset: "Zonsondergang",
    sunrise: "Zonsopgang",
    next_sun: "Volgende zonsopgang / zonsondergang",
    waiting: "Wachten op Home Assistant…",
    configure_entity: "Configureer een weerentiteit voor deze kaart.",
    entity_not_found: "Entiteit niet gevonden",
    enable_section:
      "Schakel een sectie in via de kaartconfiguratie om weer te tonen.",
    no_forecast: "Geen {mode} prognose beschikbaar op",
    forecast_failed: "Prognose laden mislukt",
    mode_daily: "dagelijkse",
    mode_hourly: "uurlijkse",
    wind: "Wind",
    wind_tip: "Wind {speed} (Beaufort {bft})",
    beaufort: "Beaufort",
    active_warnings: "{count} actieve waarschuwingen",
    alert_starts_in: "Begint over {duration}",
    alert_ends_in: "Eindigt over {duration}",
    alert_started_ago: "Begonnen {duration} geleden",
    alert_ended_ago: "Geëindigd {duration} geleden",
    chart_high: "Max",
    chart_low: "Min",
    chart_temp: "Temp",
    chart_precip: "Neerslag",
    chart_precip_pct: "Neerslag %",
    legend_general: "Algemeen",
    legend_current: "Huidig weer",
    legend_daily: "Dagelijkse prognose",
    legend_hourly: "Uurlijkse prognose",
    legend_alerts: "Weerswaarschuwingen",
    legend_actions: "Acties",
    legend_sensors: "Optionele sensoren",
    weather_entity: "Weerentiteit",
    layout: "Layout",
    layout_default: "standaard",
    layout_compact: "compact",
    layout_minimal: "minimaal",
    show_name: "Naam tonen",
    name_placeholder: "Naam (leeg = entiteitslabel)",
    icon_style: "Pictogramstijl",
    animated_icons: "Geanimeerde pictogrammen",
    animated_background: "Geanimeerde achtergrond",
    show_current_weather: "Huidig weer tonen",
    current_detail_hint:
      "Detailchips verschijnen alleen wanneer de weerentiteit of een sensor een waarde heeft.",
    preset_available_details: "Beschikbare details",
    preset_all_details: "Alle details",
    preset_clear_all: "Alles wissen",
    footnote_missing_attrs:
      "* Niet op deze weerentiteit — voeg een sensor toe onder Optionele sensoren.",
    show_daily_forecast: "Dagelijkse prognose tonen",
    days: "Dagen",
    condition_icons: "Weerpictogrammen",
    show_hourly_forecast: "Uurlijkse prognose tonen",
    hours: "Uren",
    prob_not_in_forecast: "kans niet in prognose",
    prob_in_forecast: "kans in prognose",
    rainfall: "neerslag",
    probability: "kans",
    show_weather_alerts: "Weerswaarschuwingen tonen",
    alerts_choose_hint:
      "Kies de bron. Aanbevolen: CAP Alerts. Europees alternatief: MeteoAlarm sensor.",
    alert_source: "Waarschuwingsbron",
    cap_alerts_device: "CAP Alerts-apparaat",
    alert_entities: "Waarschuwingsentiteiten",
    cap_device_hint:
      "Kies een entiteit op je CAP Alerts-apparaat. De kaart gebruikt alle actieve waarschuwingen op dat apparaat.",
    cap_device_auto: "Eén CAP Alerts-apparaat gevonden.",
    alert_entities_hint:
      "Selecteer een of meer MeteoAlarm- of CAP-entiteiten. Alle actieve waarschuwingen worden samengevoegd.",
    add_another_entity: "Nog een entiteit toevoegen",
    actions_default_hint:
      "Tikken opent standaard meer info over de weerentiteit.",
    tap_action: "Tikactie",
    hold_action: "Ingedrukt houden",
    double_tap_action: "Dubbeltikactie",
    sensors_override_hint:
      "Overschrijf waarden met aparte sensoren. Conditie-override is handig om achtergronden te testen.",
    condition: "Conditie",
    temperature: "Temperatuur",
    wind_bearing: "Windrichting (graden)",
    sun: "Zon",
    phase_new: "Nieuw",
    phase_update: "Update",
    phase_cancel: "Geannuleerd",
    phase_expired: "Verlopen",
  },
} as const;

export type LocalizeKey = keyof typeof STRINGS.en;

function localeBase(language?: string): keyof typeof STRINGS {
  if (!language) return "en";
  const base = language.split("-")[0]?.toLowerCase();
  if (base === "is" || base === "nl") return base;
  return "en";
}

export function resolveLanguage(hass?: HomeAssistant): string | undefined {
  if (!hass) return undefined;
  return (
    hass.locale?.language ?? hass.language ?? hass.config.language ?? undefined
  );
}

export function localize(
  key: LocalizeKey,
  language?: string,
  vars?: Record<string, string>,
): string {
  const lang = localeBase(language);
  let text: string = STRINGS[lang][key] ?? STRINGS.en[key];
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replace(`{${k}}`, v);
    }
  }
  return text;
}

/** Localized layout option label. */
export function layoutLabel(
  layout: string,
  language?: string,
): string {
  const key = `layout_${layout}` as LocalizeKey;
  if (key in STRINGS.en) {
    return localize(key, language);
  }
  return layout;
}
